services:
  northPrimary:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_NORTH_PRIMARY_PORT}:5432"
    volumes:
      - northPrimary_data:/var/lib/postgresql/data

  northReplica:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_NORTH_REPLICA_PORT}:5432"
    volumes:
      - northReplica_data:/var/lib/postgresql/data

  southPrimary:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_SOUTH_PRIMARY_PORT}:5432"
    volumes:
      - southPrimary_data:/var/lib/postgresql/data

  southReplica:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_SOUTH_REPLICA_PORT}:5432"
    volumes:
      - southReplica_data:/var/lib/postgresql/data

volumes:
  northPrimary_data:
  northReplica_data:
  southPrimary_data:
  southReplica_data:

